### ISSUE TITLE
What is the generator used during the white-box attack phase?

### ISSUE THREAD

**Issue by EchoLymmm** [ngoc-nguyen-0/LOKT_neurips2023#2]
Could you please confirm whether the generator used for the white-box attack on the surrogate model is the original generator from T-ACGAN, or was a new generator retrained?

**Comment by ngoc-nguyen-0** [comment]
Hi,
Only PLGMI uses the T-ACGAN for attacking. For KEDMI, we follow the paper to train a new GAN using the surrogate models. For GMI, we use the general GAN. 
Thanks.
Ngoc

**Comment by EchoLymmm** [comment]
> Hi, Only PLGMI uses the T-ACGAN for attacking. For KEDMI, we follow the paper to train a new GAN using the surrogate models. For GMI, we use the general GAN. Thanks. Ngoc

In the setup where the classifier head of the discriminator network serves as a surrogate model, is the output of the generator directly used as the images obtained in the attack?

**Comment by ngoc-nguyen-0** [comment]
No, the output images of the trained G in TACGAN are not used as the reconstructed images. We use the discriminator as a surrogate model and still performance the whitebox attack on it, similar to other surrogate models,
