### ISSUE TITLE
released pre-trained models?

### ISSUE THREAD

**Issue by baogiadoan** [ngoc-nguyen-0/LOKT_neurips2023#3]
Hi, 
Can you please help to upload the pre-trained models of GAN/classifiers/surrogate models? That would help to replicate the results faster without needing to train GAN again as it took some time to finish the training.

**Comment by ngoc-nguyen-0** [comment]
Hi,

You can download the surrogate models and TACGAN at: https://drive.google.com/drive/folders/11gvFaltjILgPmNgkJ_w1fcINj1RlfOuw?usp=sharing

Thanks,
Ngoc

**Comment by baogiadoan** [comment]
thanks, I can download now
